# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/simulation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/simulation.proto\x12\nsimulation\"\x07\n\x05\x45mpty\"\x94\x01\n\rUniverseState\x12\x0c\n\x04step\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x37\n\x07metrics\x18\x03 \x03(\x0b\x32&.simulation.UniverseState.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32Z\n\x11SimulationService\x12\x45\n\x13StreamUniverseState\x12\x11.simulation.Empty\x1a\x19.simulation.UniverseState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNIVERSESTATE_METRICSENTRY']._loaded_options = None
  _globals['_UNIVERSESTATE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=39
  _globals['_EMPTY']._serialized_end=46
  _globals['_UNIVERSESTATE']._serialized_start=49
  _globals['_UNIVERSESTATE']._serialized_end=197
  _globals['_UNIVERSESTATE_METRICSENTRY']._serialized_start=151
  _globals['_UNIVERSESTATE_METRICSENTRY']._serialized_end=197
  _globals['_SIMULATIONSERVICE']._serialized_start=199
  _globals['_SIMULATIONSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
